version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - ML_SERVICE_URL=http://ml_service:5000
    depends_on:
      - ml_service

  ml_service:
    build: ./ml_service
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
